exclude: [vendor]

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
  lab:
    output: true
    permalink: /lab/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
