github_url: https://github.com/UCSB-CS56-F17/ucsb-cs56-f17.github.io
mentor_url: https://ucsb-cs56-pconrad-mentors.github.io


piazza_url: https://piazza.com/class/j80k1o0zsxg1j7

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

ta_list: "Kevin B., Jonathan, and Yun"
ta_list_full: "Kevin Burk, Yun Suk Chang, and Jonathan Easterman"
mentors_list: "Aryaman, Joel, Johnny, Kevin L., Natasha, Sean, Scott, Steven"
discussion_section_times: "2pm, 4pm or 5pm"

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"



start_week: 0
start_date: 2017-09-24 00:00:00.00-7:00
num_weeks: 11
extra_exam_week: true
sections: "2pm,&nbsp;4pm or&nbsp;5pm"

cal_dates: >
  [
  {"label":"First day of classes", "date":"2017-09-28" },
  {"label":"Last day to drop classes via GOLD","date":"2017-10-25" },
  {"label":"Univ Holiday", "date":"2017-11-10" },
  {"label":"Clocks back 1 hour", "date":"2017-11-05" },	
  {"label":"Univ Holiday", "date":"2017-11-23" },
  {"label":"Univ Holiday", "date":"2017-11-24" },
  {"label":"Last day of classes", "date":"2017-12-08" },			
  ]


course: "CS56"
legacy_wiki_name: 56wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/56wiki" 
qtr: "F17"
quarter: "Fall 2017"
hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"

kramdown:
   parse_block_html: true


exclude:
   - vendor
   - _exam/e02/cs56_m16_e02/code
   - _exam/e01/cs56_f16_e01/code


timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  teams:
    output: true
    permalink: /teams/:path/
  lectures:
    output: true
    permalink: /lectures/:path/



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: teams
    values:
      layout: teams
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


